### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.0

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by jakirkham** [comment]
Hmm...looks like this isn't from your fork, @marscher. 😕

**Comment by marscher** [comment]
sorry, this doubles the amount of ci jobs, right?

**Comment by marscher** [comment]
This is a dependency of conda-forge/thermotools-feedstock and we have to wait until scipy is built for python3.6

**Comment by jakirkham** [comment]
> sorry, this doubles the amount of ci jobs, right?

There is that. However, it also means things deploy as soon as the CIs pass as opposed to when the PR is merged.

**Comment by marscher** [comment]
Ok, good to know (you need this for having multiple branches of majors 
of numyp I guess). I'll do the PRs from my fork in the future then.

**Pull request closed without merging**
